# Generated by Django 4.0.6 on 2022-07-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='played',
            name='play',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
