# Generated by Django 4.0.6 on 2022-07-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_played_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='played',
            name='play',
            field=models.CharField(choices=[('Y', 'Played with!'), ('N', ' Not played with!')], default='Y', max_length=1),
        ),
    ]
