# Generated by Django 4.0.6 on 2022-07-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_played_play'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='played',
            options={'ordering': ['-date']},
        ),
    ]
